// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // ✅ Disable Realtime WebSocket - fixes console errors & Best Practices score
  realtime: {
    params: {
      eventsPerSecond: -1,
    },
  },
  global: {
    headers: {
      // ✅ Identify requests clearly
      'x-application-name': 'azani-isp-project',
    },
  },
  // ✅ Disable WebSocket connection entirely
  db: {
    schema: 'public',
  },
});

// ✅ Disconnect realtime immediately to prevent WebSocket errors
supabase.realtime.disconnect();
